// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI + migrations use the DIRECT (non-pooler) Neon endpoint — standard
    // Neon practice; PgBouncer transaction mode is for the app's runtime pool.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
